export interface MangaParams {
    pageSize: number,
    pageNumber: number,
    variousName: string,
    slug: string,
    genre: string,
    status: string,
    author: string,
    popularity: number,
    publicationYear: number,
    language: string,
    rating: number,
    type: string,
    orderBy: string,
}